### ISSUE TITLE
Doesn't work properly in Visual Studio

### ISSUE THREAD

**Issue by BeichenDream** [trustedsec/COFFLoader#1]
I did a simple patch

![patch](https://user-images.githubusercontent.com/43266206/109418069-60a64f00-7a01-11eb-8ffb-0a02868963ca.jpg)

But when I run it he got an error

![error](https://user-images.githubusercontent.com/43266206/109418102-86cbef00-7a01-11eb-8298-29ac34a41c10.jpg)

This error does not appear when using x86_64-w64-mingw32-gcc

![no-bug](https://user-images.githubusercontent.com/43266206/109418139-bc70d800-7a01-11eb-95c5-86d69f62e629.jpg)

**Comment by kev169** [comment]
Can you attach the entire output of both the visual studio and mingw runs? Think I know why its happening, but want to see more before I start trying to fix it.

**Comment by BeichenDream** [comment]
The txt file is the output log, the exe is the compiled update code, and the folder is the modified Visual Studio code

[info.zip](https://github.com/trustedsec/COFFLoader/files/6057394/info.zip)

**Comment by BeichenDream** [comment]
The txt file is the output log, the exe is the compiled update code, and the folder is the modified Visual Studio code

[info.zip](https://github.com/trustedsec/COFFLoader/files/6057418/info.zip)

**Comment by BeichenDream** [comment]
I noticed that you have applied for a piece of memory for each section separately when processing sections, but only one piece of memory was applied for in the cobalt strike. Will you modify it later?

**Comment by kev169** [comment]
Ok, I think I know whats going on. Will try to add a visual studio project that it can build and run with. Probably wont be done right away. The main issue is that the COFFLoader.h structures where __attribute__((packed)) is at needs to still be packed, so will swap that out with #pragma pack(push, 1) and #pragma pop. Then I need to work on documenting what defines are needed for what architectures because I just used whatever defines mingw already has setup.

**Comment by kev169** [comment]
Fixed by 6c163398b9d23f187c0106fc4fda4b8a20a92c37
